//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.19 at 12:00:20 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.vprojects.com/bdms/patient", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.vprojects.bdms.patient;
