//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.19 at 12:00:20 PM EST 
//


package com.vprojects.bdms.patient;

public class Patient {

    protected int patientId;
    protected String bloodType;
    protected String needStatus;
    protected int weightLbs;

    /**
     * Gets the value of the patientId property.
     * 
     */
    public int getPatientId() {
        return patientId;
    }

    /**
     * Sets the value of the patientId property.
     * 
     */
    public void setPatientId(int value) {
        this.patientId = value;
    }

    /**
     * Gets the value of the bloodType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBloodType() {
        return bloodType;
    }

    /**
     * Sets the value of the bloodType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBloodType(String value) {
        this.bloodType = value;
    }

    /**
     * Gets the value of the needStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeedStatus() {
        return needStatus;
    }

    /**
     * Sets the value of the needStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeedStatus(String value) {
        this.needStatus = value;
    }

    /**
     * Gets the value of the weightLbs property.
     * 
     */
    public int getWeightLbs() {
        return weightLbs;
    }

    /**
     * Sets the value of the weightLbs property.
     * 
     */
    public void setWeightLbs(int value) {
        this.weightLbs = value;
    }

}
